site_name: Zhihao Li's Knowledge Book
site_description: Knowledge Book
site_url: https://lzhms.github.io/KBook
repo_name: LZHMS/KBook
repo_url: https://github.com/LZHMS/KBook
theme:
  name: material
  custom_dir: overrides
  language: en
  logo: images/icon.png
  favicon: images/icon.png
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to system preference
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: teal
      accent: deep purple
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - header.autohide
    - navigation.footer
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow

copyright: Copyright &copy; 2024 Zhihao Li
nav:
  - About:
    - Mission: Home/Mission.md
  - Mathematics:
    - Mathematics/index.md
    - Advanced Mathematics: Mathematics/AdvancedMathematics.md
  - Deep Learning:
    - DeepLearning/index.md
    - Basic Terms: DeepLearning/BasicTerms.md
  - Research Innovation:
    - Innovation/index.md
    - Algorithms: Innovation/Algorithms.md
    - Frameworks: Innovation/Frameworks.md
    - Data Processing: Innovation/DataProcessing.md

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: LZHMS/KBook
      branch: main
  - git-authors

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/LZHMS
    - icon: fontawesome/solid/paper-plane
      link: mailto:zhihaoli2003@outlook.com
    - icon: fontawesome/brands/mastodon
      link: https://lzhms.github.io/    

markdown_extensions:
  - tables
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - Configuration/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - Configuration/stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css